spring:
  application:
    name: "service-questionnaire-test"
  datasource:
    url: 'jdbc:postgresql://localhost:5432/test?currentSchema=public'
    username: service-questionnaire
    password: azerty

spring.jooq.sql-dialect: Postgres
spring.flyway.enabled: true

logging.exception-conversion-word: 'none'
logging.pattern.console: '%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n'
logging.pattern.file: '%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n'
logging.file.max-history: 100
logging.file.max-size: '10M'
logging.pattern.level: 'DEBUG'
logging.pattern.dateformat: '%d{HH:mm:ss.SSS}'
